version = 1

test_patterns = ["*/test/**"]

exclude_patterns = [
    "public/**",
    "dist/**",
    ".webpack/**"
]

[[analyzers]]
name = "javascript"
enabled = true
environment = ["nodejs","browser","jest"]

[analyzers.meta]
  plugins = ["react"]
  module_system = "es-modules"
  dialect = "typescript"
  skip_doc_coverage = ["class-expression", "method-definition"]
  cyclomatic_complexity_threshold = "high"
